# Generated by Django 5.2.17 on 2026-08-20 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(choices=[('flower_bucket', '抱抱桶'), ('flower_box', '花盒'), ('flower_arrangement', '花艺'), ('hand_bouquet', '手捧花'), ('perfume', '香水'), ('mini_flower', '小鼻嘎花'), ('other', '其它')], max_length=18)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time_limit_minutes', models.PositiveSmallIntegerField()),
                ('product_status', models.CharField(choices=[('on_sale', '已上架'), ('off_sale', '已下架')], default='on_sale', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=255, unique=True)),
                ('image_role', models.CharField(choices=[('main', '主图'), ('detail', '详情图')], max_length=6)),
                ('sort_order', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ['sort_order'],
                'constraints': [models.UniqueConstraint(fields=('product', 'sort_order'), name='unique_product_image_sort_order'), models.CheckConstraint(condition=models.Q(('sort_order__lte', 5)), name='product_image_sort_order_lte_check')],
            },
        ),
    ]
