# Generated by Django 5.2.17 on 2026-08-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_time_limit_minutes',
            field=models.PositiveIntegerField(),
        ),
    ]
